dist: precise
language: python

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-dev
      - expect-dev  # provides unbuffer utility
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev
      - python-libxml2

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - VERSION="10.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="odoo/odoo" UNIT_TEST="1"

virtualenv:
  system_site_packages: true


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -r requirements.txt

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
